idf_component_register(
    SRCS
        "main.cpp"
        "wifi_setup.cpp"
        "provisioning_http.cpp"
        "beam_crypto.cpp"
        "beam_protocol.cpp"
        "audio.cpp"
    INCLUDE_DIRS "."
    REQUIRES
        esp_wifi
        esp_event
        esp_netif
        nvs_flash
        mbedtls
        json
        esp_http_server
        driver
        lwip
)
